version: "3"

services:
  generate:
    build: .
    volumes:
      - /c/users/isaac bythewood/desktop/art:/data
    environment:
      - DEVICE=cuda
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
